// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whleknhrzgayybpmqdlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndobGVrbmhyemdheXlicG1xZGx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Njc3NTEsImV4cCI6MjA2MTQ0Mzc1MX0.Z3X4EKgGUglX1kw9onjw5KhPjSJxVyQ676nTDTzYwiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);